spring:
  mail:
    host: smtp.gmail.com
    username: ruamepnn@gmail.com
    password: zffsguegwylsnfak
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
