spring:
  mail:
    host: smtp.gmail.com
    username: andreimusat2000@gmail.com
    password: dely hwsy moyo xnhw
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

anagrafiche-profili:
  path-prefix: C:/Users/ruame/Desktop/
  destinazione: profili-anagrafiche/
  
  anagrafiche-profili-rapportini:
    path-prefix-rapportini: /rapportini/
  
  
  anagrafiche-profili-documenti:
   path-prefix-documenti: /documenti/image-profile.txt
  
 