spring:
  mail:
    host: smtp.gmail.com
    username: andreimusat2000@gmail.com
    password: dely hwsy moyo xnhw
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true